### ISSUE TITLE
arm-elf-gcc from Homebrew and APT doesn't work.

### ISSUE THREAD

**Issue by georgemorgan** [flipper-io/flipper#109]
Invalid firmware images are generated from the stock toolchains installed by these package managers.

**Comment by nicholastmosher** [comment]
I believe we've fixed this issue by fixing some flags in the makefile. I think it was [this commit](https://github.com/flipper-io/flipper/commit/dd96a046b0003bdd152db3fd43d9914b718c8bed). I've had a bunch of people successfully build and flash the atsam4s firmware in the past week, so I'm going to mark this as resolved.
